# Site settings
title: My Data Analysis Portfolio
description: A portfolio showcasing my data analysis projects and Tableau visualizations.
url: https://yourusername.github.io/Data-Analysis-Portfolio
baseurl: ""

# Author settings
author:
  name: Jaedon Jensen
  # email: your.email@example.com

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed # Enables RSS feed for your site

# Social media links
social:
  linkedin: https://www.linkedin.com/in/jaedonjensen/
  github: https://github.com/jaedonjensen/

# Navigation settings
navigation:
  - title: Home
    url: /
  #- title: Projects
  #  url: /projects/
  #- title: Contact
  #  url: /contact/
